github_url = "https://github.com/jneug/schule-typst/"

[version]
current = "0.1.0"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "typst.toml"
search = 'version = "{current_version}"'

[[file]]
src = "README.md"
search = "({current_version})"
# [[file]]
# src = "README.md"
# search = "typopts:{current_version}"
# [[file]]
# src = "README.md"
# search = "typopts-{current_version}"
# [[file]]
# src = "README.md"
# search = "v{current_version}"

[[file]]
src = "docs/schule-manual.typ"
search = 'version:\s*"{current_version}",'
[[file]]
src = "docs/schule-manual.typ"
search = 'schule:{current_version}'

[[file]]
src = "examples/*.typ"
search = 'schule:{current_version}'

# [[before_commit]]
# name = "create local version"
# #cmd = "mkdir ../schule-{new_version}; cp ./* ../schule-{new_version}"
# cmd = "ln -s schule ../schule-{new_version}"
[[before_commit]]
name = "compile examples (pdf)"
cmd = "for f in examples/*.typ; typst compile --root . $f; end"
[[before_commit]]
name = "compile examples (svg)"
cmd = "for f in examples/*.typ; typst compile --root . -f svg $f (string replace '.typ' -- '-{n}.svg' $f); end"
[[before_commit]]
name = "compile manual"
cmd = "typst compile --root . docs/schule-manual.typ"
